# workflow for log pull request between two tags
name: Python log

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./python


jobs:
  log:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get pr collection
        id: get-pr
        env:
          REPO: ${{ github.repository }}
          QF_GITHUB_TOKEN: ${{ secrets.QF_GITHUB_TOKEN }}
        run: |
          bash ./scripts/release_note.sh python
          echo "release note path:"
          echo body_path=$(realpath ./release_note.md) >> $GITHUB_OUTPUT
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: "test"
          token: ${{ secrets.QF_GITHUB_TOKEN }}
          draft: false
          bodyFile: ${{ steps.get-pr.outputs.body_path }}
#          generateReleaseNotes: true
          tag: "py/v0.3.6"
          prerelease: false
