name: Notebook CI

on:
#  push:   # 只有push触发
#    paths:
#      - 'cookbook/**/*.ipynb'  # cookbook目录下所有ipynb文件有改动时触发
#      - '!cookbook/.ipynb_checkpoints/**'  # 排除.ipynb_checkpoints目录下所有文件
  workflow_call:  # 手动触发inputs:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      ntbk-path:
        type: string

defaults:
  run:
    shell: bash  # 默认shell为bash
    working-directory: ./cookbook  # 默认工作目录为cookbook

env:
  RUFF_OUTPUT_FORMAT: github


jobs:
  test:
    name: Notebook Unit Tests
    runs-on: ${{ inputs.os }}
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
#       获取commit内容
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{inputs.python-version}}
          # poetry 安装库
#      - name: Install Poetry
#        run: |
#          pip install poetry
#          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
#          poetry lock
#      - name: Get Poetry version
#        run: poetry --version
#      - name: Setup Python Cache
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{matrix.python-version}}
#          cache: "poetry"
#      - name: Install deps
#        run: |
#          make install
          # 手动安装库
      - name: pip_install
        run: |
          python3 -m pip install papermill ipykernel nbformat nbconvert pytest pytest-asyncio qianfan
          python3 -m pip install langchain==0.1.7 chromadb pdfplumber datasets duckduckgo_search
          python3 -m pip install pillow
          python3 -m ipykernel install --user
      - name: install_RAG
        if: ${{ inputs.ntbk_path == 'cookbook/RAG'}}
        run: |
          echo "install RAG"
